services:
  livekit:
    image: livekit/livekit-server:v1.7.2
    container_name: livekit-server
    ports:
      - "7880:7880"
      - "7881:7881/udp"
      - "7882:7882"

    environment:
      - LIVEKIT_PORT=7880
      - LIVEKIT_BIND_ADDRESSES=0.0.0.0
      - LIVEKIT_RTC_TCP_PORT=7882
      - LIVEKIT_RTC_UDP_PORT=7881

      - LIVEKIT_REDIS_ADDRESS=redis:6379
      - "LIVEKIT_KEYS=testkey: akQ2cFd4OEx0UDlyWmU3MnNZcTNtWGZOdEE0a1Z1MTIzCg=="
      - LIVEKIT_LOG_LEVEL=debug
      - LIVEKIT_DEVELOPMENT=true
      - LIVEKIT_ROOM_AUTO_CREATE=true
      - LIVEKIT_ROOM_MAX_PARTICIPANTS=100
      - LIVEKIT_ALLOWED_ORIGINS=http://localhost:4200
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - skillsharing-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7880/" ]  # Endpoint spécifique à LiveKit
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s  # Augmentez le délai initial
  redis:
    image: redis:7-alpine
    container_name: livekit-redis
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - skillsharing-net
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - skillsharing-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - skillsharing-net
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alibou
      - MONGO_INITDB_ROOT_PASSWORD=alibou

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8091:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - skillsharing-net




  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - skillsharing-net
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - skillsharing-net

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - skillsharing-net
    command:
      - "start-dev"

  prosody:
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - JICOFO_COMPONENT_SECRET=jitsi_jicofo_secret_2025
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=focus_auth_2025
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=jvb_auth_2025
      - JWT_APP_ID=skill_sharing_app
      - JWT_ASAP_KEYSERVER=http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs
      - JWT_ACCEPTED_ISSUERS=http://localhost:9098/realms/skill-sharing
      - JWT_ACCEPTED_AUDIENCES=meet.jitsi
    networks:
      - skillsharing-net

  jicofo:
      image: jitsi/jicofo:stable
      container_name: jitsi-jicofo
      restart: unless-stopped
      environment:
        - XMPP_DOMAIN=meet.jitsi
        - XMPP_AUTH_DOMAIN=auth.meet.jitsi
        - XMPP_SERVER=prosody
        - JICOFO_COMPONENT_SECRET=jitsi_jicofo_secret_2025
        - JICOFO_AUTH_USER=focus
        - JICOFO_AUTH_PASSWORD=focus_auth_2025
      depends_on:
        - prosody
      networks:
        - skillsharing-net

  jvb:
      image: jitsi/jvb:stable
      container_name: jitsi-jvb
      restart: unless-stopped
      ports:
        - "10000:10000/udp"
      environment:
        - DOCKER_HOST_ADDRESS=localhost
        - XMPP_AUTH_DOMAIN=auth.meet.jitsi
        - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
        - XMPP_SERVER=prosody
        - JVB_AUTH_USER=jvb
        - JVB_AUTH_PASSWORD=jvb_auth_2025
        - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
      depends_on:
        - prosody
      networks:
        - skillsharing-net

  jibri:
    image: jitsi/jibri:stable
    container_name: jitsi-jibri
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_BIND_SERVICE  # Nouvelle capacité
    devices:
      - "/dev/snd:/dev/snd"  # Accès aux périphériques audio
    environment:
      - JIBRI_API_URL=http://jibri:2222
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=prosody
      - JIBRI_XMPP_USER=jibri
      - JIBRI_XMPP_PASSWORD=jibri_xmpp_2025
      - JIBRI_RECORDER_USER=recorder
      - JIBRI_RECORDER_PASSWORD=recorder_2025
      - JIBRI_BREWERY_MUC=jibribrewery@internal-muc.meet.jitsi  # Ajout crucial
      - JIBRI_RECORDING_DIR=/config/recordings
      - DISPLAY=:0
      - CHROME_FLAGS="--disable-setuid-sandbox --no-sandbox"
    volumes:
      - ./recordings:/config/recordings  # Chemin absolu recommandé
      - /dev/shm:/dev/shm
    depends_on:
      - prosody
    networks:
      - skillsharing-net

  web:
      image: jitsi/web:stable
      container_name: jitsi-web
      restart: unless-stopped
      ports:
        - "8010:80"
      environment:
        - ENABLE_AUTH=1
        - ENABLE_GUESTS=1
        - AUTH_TYPE=jwt
        - JWT_APP_ID=skill_sharing_app
        - JWT_ASAP_KEYSERVER=http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs
        - JWT_ACCEPTED_ISSUERS=http://localhost:9098/realms/skill-sharing
        - JWT_ACCEPTED_AUDIENCES=meet.jitsi
        - XMPP_DOMAIN=meet.jitsi
        - XMPP_SERVER=prosody
        - XMPP_BOSH_URL_BASE=http://prosody:5280
        - ENABLE_RECORDING=1
        - JIBRI_BREWERY_MUC=jibribrewery@internal-muc.meet.jitsi
        - JIBRI_PENDING_TIMEOUT=90
        - ENABLE_MODERATION=1
      depends_on:
        - prosody
        - jicofo
        - jvb
        - keycloak
      networks:
        - skillsharing-net

networks:
  skillsharing-net:
    driver: bridge


volumes:
  postgres:
  pgadmin:
  mongo:
  jibri:
  redis_data: