spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay


        - id: service-skill
          uri: lb://SERVICE-SKILL
          predicates:
            - Path=/api/v1/skills/**,/api/v1/categories/**
          filters:
            - TokenRelay


        - id: service-exchange
          uri: lb://SERVICE-EXCHANGE
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - TokenRelay

        - id: keycloak-auth
          uri: http://localhost:9098
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /realms/skill-sharing/\${segment}

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/skill-sharing
          jwk-set-uri: http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs


keycloak:
  auth-server-url: http://localhost:9098
  realm: skill-sharing
  client-id: gateway-service
  client-secret: oLdwxIS2DaNSeELasubWHBTCRUEIvpEF

server:
  port: 8822