spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "ws://localhost:4200"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allow-credentials: true
            exposed-headers:
              - "Authorization"

      discovery:
        locator:
          enabled: true

      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay

        - id: service-skill
          uri: lb://SERVICE-SKILL
          predicates:
            - Path=/api/v1/skills/**,/api/v1/categories/**
          filters:
            - TokenRelay

        - id: service-exchange
          uri: lb://SERVICE-EXCHANGE
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - TokenRelay

        - id: service-user-uploads
          uri: lb://SERVICE-USER
          predicates:
            - Path=/uploads/**
          filters:
            - RewritePath=/uploads/(?<segment>.*), /uploads/${segment}

        - id: service-skill-uploads
          uri: lb://SERVICE-SKILL
          predicates:
            - Path=/skill-uploads/**
          filters:
            - RewritePath=/skill-uploads/(?<segment>.*), /skill-uploads/${segment}

        - id: notification-service-http
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - TokenRelay

        - id: notification-service-websocket
          uri: lb://notification-service
          predicates:
            - Path=/ws/notifications/**
          filters:
            -  RewritePath=/ws/notifications, /ws/notifications
        - id: service-livestream-http
          uri: lb://SERVICE-LIVESTREAM
          predicates:
            - Path=/api/v1/livestream/**
          filters:
            - TokenRelay

        - id: livekit-http-api
          uri: http://localhost:7880
          predicates:
            - Path=/livekit/**
          filters:
            - StripPrefix=1


            # Route critique pour WebSocket LiveKit
        - id: livekit-websocket-direct
          uri: ws://localhost:7880
          predicates:
            - Path=/rtc,/rtc/**
          filters:
            - StripPrefix=1


        - id: service-livestream-websocket
          uri: lb://SERVICE-LIVESTREAM
          predicates:
            - Path=/ws,/ws/websocket,/ws/info,/ws/info/**
          filters:
            - TokenRelay



        - id: service-messagerie-http
          uri: lb://SERVICE-MESSAGERIE
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - TokenRelay

        - id: service-messagerie-websocket
          uri: lb:ws://SERVICE-MESSAGERIE
          predicates:
            - Path=/ws/messaging/**
          filters:
            - RewritePath=/ws/messaging/(?<segment>.*), /ws/${segment}

        - id: service-messagerie-uploads
          uri: lb://SERVICE-MESSAGERIE
          predicates:
            - Path=/message-uploads/**
          filters:
            - RewritePath=/message-uploads/(?<segment>.*), /message-uploads/${segment}

        - id: service-messagerie-sockjs-info
          uri: lb://SERVICE-MESSAGERIE
          predicates:
              - Path=/ws/messaging/info/**
          filters:
              - RewritePath=/ws/messaging/info(?<segment>.*), /ws/info${segment}








  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/skill-sharing
          jwk-set-uri: http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:9098
  realm: skill-sharing
  client-id: backend-service
  client-secret: ifUlRmmtEfu02d80iz06MroNHC5kVuKf

server:
  port: 8822

notification:
  websocket:
    endpoint: /ws

livekit:
  url: ws://localhost:7880
  api-key: testkey
  api-secret: akQ2cFd4OEx0UDlyWmU3MnNZcTNtWGZOdEE0a1Z1MTIzCg==
  server-url: http://localhost:7880
  cors:
    allowed_origins:
      - "http://localhost:4200"
      - "ws://localhost:4200"

  rtc:
    udp_port: 7881
    port_range:
      start: 50000
      end: 50100
    ice_servers:
      - urls: "stun:stun.l.google.com:19302"
      - urls: "stun:stun1.l.google.com:19302"
      - urls: "turn:openrelay.metered.ca:443?transport=tcp"
        username: "openrelayproject"
        credential: "openrelayproject"


  turn:
    enabled: true

  tls:
    enabled: false

  room:
    max_participants: 50
    empty_timeout: 300
    max_duration: 7200
    auto_create: true

  token:
    ttl: 86400
    publisher_ttl: 172800

  recording:
    enabled: true
    storage-path: ./recordings
    max-size: 1GB
    format: mp4
    realistic-simulation: true

