spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers: "Authorization"
      discovery:
        locator:
          enabled: true

      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay

        - id: service-skill
          uri: lb://SERVICE-SKILL
          predicates:
            - Path=/api/v1/skills/**,/api/v1/categories/**
          filters:
            - TokenRelay

        - id: service-exchange
          uri: lb://SERVICE-EXCHANGE
          predicates:
            - Path=/api/v1/exchanges/**
          filters:
            - TokenRelay

        - id: service-user-uploads
          uri: lb://SERVICE-USER
          predicates:
            - Path=/uploads/**
          filters:
            - RewritePath=/uploads/(?<segment>.*), /uploads/${segment}

        - id: service-skill-uploads
          uri: lb://SERVICE-SKILL
          predicates:
            - Path=/skill-uploads/**
          filters:
            - RewritePath=/skill-uploads/(?<segment>.*), /skill-uploads/${segment}

        - id: notification-service-http
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - TokenRelay

        - id: notification-service-websocket
          uri: lb://notification-service
          predicates:
            - Path=/ws/notifications/**
          filters:
            -  RewritePath=/ws/notifications, /ws/notifications

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/skill-sharing
          jwk-set-uri: http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:9098
  realm: skill-sharing
  client-id: backend-service
  client-secret: wqKaJixE2KzSlyB7wIBqnS4DI3wQJKrz

server:
  port: 8822

notification:
  websocket:
    endpoint: /ws
