server:
  port: 8822

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Activation de la découverte dynamique des services via Eureka
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/v1/users/**

        - id: service-skill
          uri: lb://SERVICE-SKILL  #  pour le load balancing
          predicates:
            - Path=/api/v1/categories/**,/api/v1/skills/**

        - id: service-exchange
          uri: lb://SERVICE-EXCHANGE
          predicates:
            - Path=/api/v1/exchanges/**