server:
  port: 8040

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/SkillSharing_Notifications
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.notification.event,com.example.serviceexchange.dto
    template:
      default-topic: notifications

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:contact.skillsharing@gmail.com}
    password: ${MAIL_PASSWORD:ifgxdvzotonorvzz}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:9098}
  realm: skill-sharing
  client-id: backend-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET:wqKaJixE2KzSlyB7wIBqnS4DI3wQJKrz}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.mail: DEBUG
    org.springframework.kafka: DEBUG
    com.example.notification: DEBUG
  file:
    name: logs/notification-service.log