server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SkillSharing_Skills
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/skill-sharing
          jwk-set-uri: http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload-dir: ./skill-uploads
  max-size: 10MB
  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
keycloak:
  auth-server-url: http://localhost:9098
  realm: skill-sharing
application:
  config:
    User-url: http://localhost:8822/api/v1/users
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000