spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://localhost:5432/SkillSharing_User
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8222