spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://localhost:5432/SkillSharing_User
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/skill-sharing
          jwk-set-uri: http://localhost:9098/realms/skill-sharing/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"

keycloak:
  auth-server-url: http://localhost:9098
  realm: skill-sharing
  client-id: backend-service
  client-secret: wqKaJixE2KzSlyB7wIBqnS4DI3wQJKrz
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin

file:
  upload-dir: ./uploads
  max-size: 5MB

server:
  port: 8081


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.serviceuser: DEBUG
  file:
    name: logs/service-user.log