spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: service-skill
  main:
    allow-bean-definition-overriding: true
logging:
      level:
        org:
          springframework:
            security: DEBUG
            cloud:
              gateway: DEBUG
          keycloak: DEBUG
eureka:
      instance:
        lease-renewal-interval-in-seconds: 10  # Send heartbeats every 10 seconds
        lease-expiration-duration-in-seconds: 30  # Mark instance as expired after 30 seconds if no heartbeats are received
      client:
        registry-fetch-interval-seconds: 10  # Fetch registry updates every 10 seconds

